server:
  port: 8086

spring:
  webflux:
    base-path: /search
    exception-detail-logging: true

  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
          connection-timeout: 30s
          socket-timeout: 30s

    redis:
      host: localhost
      port: 6370
      password: ${REDIS_PASSWORD}
      timeout: 2000

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: default-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.dauducbach.event"


app:
  datacenter-id: 3
  worker-id: 2