server:
  port: 8087

spring:
  webflux:
    base-path: /match
    exception-detail-logging: true

  data:
    redis:
      host: localhost
      port: 6370
      password: ${REDIS_PASSWORD}
      timeout: 2000

    mongodb:
      uri: ${MONGODB_URI_MATCH_SERVICE}

    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
          connection-timeout: 30s
          socket-timeout: 30s

app:
  datacenter-id: 2
  worker-id: 1
